name: Build NuttX for Raspberry Pi Pico

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # サブモジュールを初期化

    - name: 依存関係インストール
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc-arm-none-eabi cmake git
        git clone https://github.com/raspberrypi/pico-sdk.git
        git clone https://github.com/simasimanekonya/Lite-unix-based-on-nuttix nuttx
        git clone https://github.com/simasimanekonya/Lite-unix-based-on-nuttix-apps apps
        export PICO_SDK_PATH=~/pico-sdk
        git clone https://github.com/tienson/kconfig.git
        cd kconfig
        make
        sudo make install

    - name: Configure NuttX for Raspberry Pi Pico
      run: |
        cd ~/nuttix
        ln -s external/nya nya
        ./tools/configure.sh raspberrypi-pico:usbnsh

    - name: Build NuttX
      run: |
        cd nuttix
        make

    - name: Upload UF2 file
      uses: actions/upload-artifact@v3
      with:
        name: nuttx-pico
        path: Lite-unix-based-on-nuttix/nuttx.uf2
