name: Build NuttX for Raspberry Pi Pico

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # サブモジュールを初期化

    - name: 依存関係インストール
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc-arm-none-eabi cmake git
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF0F382A1A7B6500
        sudo apt update
        sudo apt install bison flex gettext libncurses5-dev gperf automake libtool pkg-config
        sudo ln -s /usr/bin/aclocal /usr/bin/aclocal-1.15
        sudo ln -s /usr/bin/automake /usr/bin/automake-1.15
        git clone https://github.com/raspberrypi/pico-sdk.git
        export PICO_SDK_PATH=~/pico-sdk
        git clone https://bitbucket.org/nuttx/tools.git
        cd tools/kconfig-frontends/
        ./configure --enable-mconf --disable-nconf --disable-gconf --disable-qconf
        make
        sudo make install
        sudo /sbin/ldconfig
        git clone https://github.com/simasimanekonya/Lite-unix-based-on-nuttix Lite-unix-based-on-nuttix
        git clone https://github.com/simasimanekonya/Lite-unix-based-on-nuttix-apps Lite-unix-based-on-nuttix-apps
        ls
    - name: Configure NuttX for Raspberry Pi Pico
      run: |
        cd ~/Lite-unix-based-on-nuttix
        ln -s external/nya nya
        ./tools/configure.sh raspberrypi-pico:usbnsh

    - name: Build NuttX
      run: |
        cd ~/Lite-unix-based-on-nuttix
        make

    - name: Upload UF2 file
      uses: actions/upload-artifact@v3
      with:
        name: nuttx-pico
        path: Lite-unix-based-on-nuttix/nuttx.uf2
